### ISSUE TITLE
参数可以改一下

### ISSUE THREAD

**Issue by chenfusheng** [AndSync/XPermissionUtils#1]
既然requestPermissions(Context context, int requestCode, String[] permissions, OnPermissionListener listener)第一个参数必须为一个Activity，那为何不直接限制为这个参数为Activity呢？调用者也不会因为这个传入了错误的参数，例如Application？

**Comment by AndSync** [comment]
好吧 这个我确实考虑过 最终还是选择了Context 可能是跟个人习惯有关吧
在项目中大多数用的都是Context  比如在基类里面会有一个Context，比如Adapter里面很多人会传入Context用来加载布局而不是Activity ，在自定义View里面getContext()等等。。。
如果使用Activity 那么可能在传参的时候需要写上(Activity) context，或者(Activity)getContext()，为了方便 就用Context了，仅此而已，当然 你也可以改成Activity
因为最终Context(Activity)的作用只是`((Activity) context).requestPermissions(deniedPermissions
                        .toArray(new String[deniedPermissions.size()]), requestCode);`
这就是两种思想的碰撞
1、要么在调用前转换好给我
2、要么你传给我我做下校验并转换
在这里我选择了2

**Comment by freefly2016** [comment]
小米的定位 拒绝后 怎么办 怎么不提示弹窗

**Comment by AndSync** [comment]
不知道你的小米是什么版本的系统。应该不只小米手机，所有的手机都是这样的
如果是6.0以上系统会进入到onPermissionDenied方法，即未开启定位， 弹出提示框
如果是6.0以下的都会进入onPermissionGranted方法，也就是6.0以下是不能判断是否授权成功的，因此都会进入获取成功流程。这就需要自己判断了，比如定位成功后将位置信息在本地保存 可以检测这个数据是否存在来判断
