### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by hnshilei** [AndSync/XPermissionUtils#6]
add "compile 'com.xxx.xxx:xx'"??

or direct import your source code ?

**Comment by AndSync** [comment]
sorry ,I will add the gradle  "compile 'com.xxx.xxx:xx'"support soon .Now you can only copy the source code into your project.

**Comment by AndSync** [comment]
@hnshilei 
1、gradle引入
```
dependencies {
    compile 'com.andsync.xpermission:XPermissionUtils:1.1'
}
```
2、Maven引入
```
<dependency>
  <groupId>com.andsync.xpermission</groupId>
  <artifactId>XPermissionUtils</artifactId>
  <version>1.1</version>
  <type>pom</type>
</dependency>
```
