### ISSUE TITLE
报了这个错是咋回事? 

### ISSUE THREAD

**Issue by geekqian** [AndSync/XPermissionUtils#8]
`reject to start activity: Intent { act=android.intent.action.CALL dat=tel:xxxxx`

调用的直接拨打电话的权限, 号码没错, 调用步骤也按照 XPermissionUtils 的要求来, 1. 清单文件加入权限. 2.基类重写回调. 3. 调用(后来直接拷demo代码去试)... 
然后一直报这个错, 但是奇葩的是, 直接在把demo跑到手机上发现是能用的. 这个让我情何以堪... 所以问下还有哪个细节我没注意?  
补充:  第一个参数确实为 Actvity .

**Comment by AndSync** [comment]
@geekqian 不好意思 回复晚了，解决了吗？ 这个没遇到过，我也不清楚什么原因啊

**Comment by geekqian** [comment]
@AndSync 已解决, 是电话号码格式的问题. 格式不对会报这种错误.
