### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by lovedabaozi** [AndSync/XPermissionUtils#9]

**Comment by AndSync** [comment]
不同手机对权限处理流程会有不同，根据我的不完全统计基本上分三种
1、原生系统、华为手机等：有“不再提示”选项框，走标准流程
2、小米、魅族等：没有“不再提示”选项框、会一直返回false，即只要拒绝就是彻底拒绝。（不过新版MIUI9发现又按标准流程走了）
3、三星等机型：没有“不再提示”选项框，会一致返回true，即永远不会彻底拒绝

**Comment by lovedabaozi** [comment]
get！ thanks
